/*
 * This file is generated by a tool YIM.Tools.TypeScriptGenerator. Don't edit this file!
*/

class ModelHelper
{
   public static emptyDate: Date = new Date(1900, 0, 0);
}

export class ProblemDetails
{
    constructor(init?: Partial<ProblemDetails>)
    {
        Object.assign(this, init);
    }

    detail: string | null = null;
    instance: string | null = null;
    status: number | null = null;
    title: string | null = null;
    type: string | null = null;
}

export class WebResource
{
    constructor(init?: Partial<WebResource>)
    {
        Object.assign(this, init);
    }

    _links!: Record<string, WebLink>;
}

export class Address
{
    constructor(init?: Partial<Address>)
    {
        Object.assign(this, init);
    }

    countryCode!: string;
    locality!: string;
    postalCode!: string;
    streetAddress!: string;
}

export class AspectRatio
{
    constructor(init?: Partial<AspectRatio>)
    {
        Object.assign(this, init);
    }

    height = 0;
    width = 0;
}

export class DateTimePeriod
{
    constructor(init?: Partial<DateTimePeriod>)
    {
        Object.assign(this, init);
    }

    from: Date | null = null;
    to: Date | null = null;
}

export class FileReference
{
    constructor(init?: Partial<FileReference>)
    {
        Object.assign(this, init);
    }

    name!: string;
    storageId!: string;
}

export class LocalizableText
{
    constructor(init?: Partial<LocalizableText>)
    {
        Object.assign(this, init);
    }

    text!: string;
    translations: Translation[] = [];
}

export class PageRequest
{
    constructor(init?: Partial<PageRequest>)
    {
        Object.assign(this, init);
    }

    orderBy: string | null = null;
    page: number | null = null;
    pageSize: number | null = null;
    search: string | null = null;
}

export class PartialDate
{
    constructor(init?: Partial<PartialDate>)
    {
        Object.assign(this, init);
    }

    day: number | null = null;
    month: number | null = null;
    year = 0;
}

export class Period
{
    constructor(init?: Partial<Period>)
    {
        Object.assign(this, init);
    }

    from: Date = ModelHelper.emptyDate;
    to: Date = ModelHelper.emptyDate;
}

export class PhoneNumber
{
    constructor(init?: Partial<PhoneNumber>)
    {
        Object.assign(this, init);
    }

    countryCode = 0;
    nationalNumber!: string;
    regionCode!: string;
}

export class PixelSize
{
    constructor(init?: Partial<PixelSize>)
    {
        Object.assign(this, init);
    }

    height = 0;
    width = 0;
}

export class RoutesResource
{
    constructor(init?: Partial<RoutesResource>)
    {
        Object.assign(this, init);
    }

    routes!: Record<string, string>;
}

export class State<TState>
{
    constructor(init?: Partial<State<TState>>)
    {
        Object.assign(this, init);
    }

    label!: string;
    value!: any;
}

export class Translation
{
    constructor(init?: Partial<Translation>)
    {
        Object.assign(this, init);
    }

    languageCode!: string;
    text!: string;
}

export class ValidationResource
{
    constructor(init?: Partial<ValidationResource>)
    {
        Object.assign(this, init);
    }

    errors!: Record<string, string[]>;
    isValid = false;
}

export class ValueObject
{
    constructor(init?: Partial<ValueObject>)
    {
        Object.assign(this, init);
    }
}

export class WebLink
{
    constructor(init?: Partial<WebLink>)
    {
        Object.assign(this, init);
    }

    rel!: string;
    href!: string;
}

export class HttpValidationProblemDetails extends ProblemDetails
{
    constructor(init?: Partial<HttpValidationProblemDetails>)
    {
        super();
        Object.assign(this, init);
    }

    errors!: Record<string, string[]>;
}

export class PageResource<TResourceItem> extends WebResource
{
    constructor(init?: Partial<PageResource<TResourceItem>>)
    {
        super();
        Object.assign(this, init);
    }

    items: TResourceItem[] = [];
    pageNumber = 0;
    pageSize = 0;
    totalCount: number | null = null;
}

export class ValidationProblemDetails extends HttpValidationProblemDetails
{
    constructor(init?: Partial<ValidationProblemDetails>)
    {
        super();
        Object.assign(this, init);
    }
}

export enum AuthorizationScheduleType
{
    DaySchedule = 0,
    MaxOneDayTimeSchedule = 1,
}

