/*
 * This file is generated by a tool YIM.Tools.TypeScriptGenerator. Don't edit this file!
*/

import
{
    WebResource,
    PhoneNumber
} from '@src/models/generated/common';

class ModelHelper
{
   public static emptyDate: Date = new Date(1900, 0, 0);
}

export class AddPasswordRequest
{
    constructor(init?: Partial<AddPasswordRequest>)
    {
        Object.assign(this, init);
    }

    newPassword: string | null = null;
}

export class AddTenantUserRequest
{
    constructor(init?: Partial<AddTenantUserRequest>)
    {
        Object.assign(this, init);
    }

    emailAddress: string | null = null;
    fullName!: string;
    inviteEmailType: UserInviteEmailType = UserInviteEmailType.None;
    languageCode: string | null = null;
    phoneNumber: PhoneNumber | null = null;
    validTo: Date | null = null;
}

export class UpdatePasswordRequest
{
    constructor(init?: Partial<UpdatePasswordRequest>)
    {
        Object.assign(this, init);
    }

    newPassword: string | null = null;
    oldPassword: string | null = null;
}

export class UpdateProfileLanguageRequest
{
    constructor(init?: Partial<UpdateProfileLanguageRequest>)
    {
        Object.assign(this, init);
    }

    languageCode!: string;
}

export class UpdateProfileRequest
{
    constructor(init?: Partial<UpdateProfileRequest>)
    {
        Object.assign(this, init);
    }

    fullName: string | null = null;
    languageCode: string | null = null;
    phoneNumber: PhoneNumber | null = null;
}

export class UpdateTenantUserRequest
{
    constructor(init?: Partial<UpdateTenantUserRequest>)
    {
        Object.assign(this, init);
    }

    fullName!: string;
    languageCode: string | null = null;
    phoneNumber: PhoneNumber | null = null;
    validTo: Date | null = null;
}

export class TenantUserDetailResource extends WebResource
{
    constructor(init?: Partial<TenantUserDetailResource>)
    {
        super();
        Object.assign(this, init);
    }

    createdOnUtc: Date = ModelHelper.emptyDate;
    emailAddress: string | null = null;
    employeeId: string | null = null;
    fullName: string | null = null;
    hasPassword = false;
    isRegistrationPending: boolean | null = null;
    isRegistrationWithAccreditationPending: boolean | null = null;
    languageCode!: string;
    modifiedOnUtc: Date = ModelHelper.emptyDate;
    phoneNumber: PhoneNumber | null = null;
    tenantId!: string;
    userId!: string;
    validTo: Date | null = null;
}

export class TenantUserListResource extends WebResource
{
    constructor(init?: Partial<TenantUserListResource>)
    {
        super();
        Object.assign(this, init);
    }

    createdOnUtc: Date = ModelHelper.emptyDate;
    emailAddress: string | null = null;
    fullName: string | null = null;
    modifiedOnUtc: Date = ModelHelper.emptyDate;
    tenantId!: string;
    userId!: string;
}

export class TermsOfUseResource extends WebResource
{
    constructor(init?: Partial<TermsOfUseResource>)
    {
        super();
        Object.assign(this, init);
    }

    termsOfUse!: string;
    termsOfUseAcceptedOn: Date | null = null;
    termsOfUsePublishedOn: Date | null = null;
}

export enum UserInviteEmailType
{
    None = 0,
    InviteOnly = 1,
    InviteWithActivation = 2,
}

